<a href="https://colab.research.google.com/github/AlhanoufIB/IT326Project/blob/main/Reports/Phase1_(6).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Phase1**

The goal of this project is to classify loan applicants into high or low credit risk categories with greater accuracy and fairness.  By finding patterns in applicant characteristics and clustering individuals with similar financial profiles, we aim to help financial institutions reduce risk while promoting fairer access to credit for applicants.


**Dataset**


German credit risk dataset
URL: https://www.kaggle.com/datasets/kabure/german-credit-data-with-risk


`we read the dataset and imported pandas`

In [ ]:
import pandas as pd

df = pd.read_csv("/content/german_credit_data.csv")

### Dataset Description

- **Number of records (instances):** 1000  
- **Number of attributes (columns):** 11  
- **Class Lable**: Risk
- **Data types of attributes:**  
  - `int64`: 5 attributes  
  - `object`: 6 attributes  
  

**Brief note:**  
This dataset contains 1000 rows and 11 columns.  
It includes 5 numerical attributes (int64) and 6 categorical/text attributes (object).  
The numerical features represent measurable values, while the categorical features represent descriptive information.


In [ ]:



print("Dataset rows,Columns:",df.shape,"\n")
#No of rows and colums
  #type of data in the dataset
print("The first 5 rows")
df.head()        #gives you the first 5 rows




Dataset rows,Columns: (1000, 11) 

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Unnamed: 0        1000 non-null   int64 
 1   Age               1000 non-null   int64 
 2   Sex               1000 non-null   object
 3   Job               1000 non-null   int64 
 4   Housing           1000 non-null   object
 5   Saving accounts   817 non-null    object
 6   Checking account  606 non-null    object
 7   Credit amount     1000 non-null   int64 
 8   Duration          1000 non-null   int64 
 9   Purpose           1000 non-null   object
 10  Risk              1000 non-null   object
dtypes: int64(5), object(6)
memory usage: 86.1+ KB
The first 5 rows


Unnamed: 0  Age     Sex  Job Housing Saving accounts Checking account  \
0           0   67    male    2     own             NaN           little   
1           1   22  female    2     own          little         moderate   
2           2   49    male    1     own          little              NaN   
3           3   45    male    2    free          little           little   
4           4   53    male    2    free          little           little   

   Credit amount  Duration              Purpose  Risk  
0           1169         6             radio/TV  good  
1           5951        48             radio/TV   bad  
2           2096        12            education  good  
3           7882        42  furniture/equipment  good  
4           4870        24                  car   bad

In [ ]:
attribute_info=pd.DataFrame(
    {
        'attributeName':df.columns,
        'dataType':df.dtypes.values
    }
)
print("\nAttribute information:\n")
print(attribute_info)



Attribute information:

       attributeName dataType
0         Unnamed: 0    int64
1                Age    int64
2                Sex   object
3                Job    int64
4            Housing   object
5    Saving accounts   object
6   Checking account   object
7      Credit amount    int64
8           Duration    int64
9            Purpose   object
10              Risk   object


In [ ]:
print(f"Number of attributes:  {len(df.columns)}")
print(f"Number of Recordes:  {len(df)}")

Number of attributes:  11
Number of Recordes:  1000
Class Lable:
Risk
good    700
bad     300
Name: count, dtype: int64


In [ ]:
print("Number of customers in each Risk category:")
risk_counts = df['Risk'].value_counts()
print(risk_counts)

print("\nPercentage of each category:")
risk_percentages = df['Risk'].value_counts(normalize=True) * 100
print(risk_percentages.round(2))

Number of customers in each Risk category:
Risk
good    700
bad     300
Name: count, dtype: int64

Percentage of each category:
Risk
good    70.0
bad     30.0
Name: proportion, dtype: float64


This section examines the distribution of the target variable we aim to predict: the Risk column.

# ***Results:***
*   The number of customers categorized as **"Good"** credit risk: **700**
*   The number of customers categorized as **"Bad"** credit risk: **300**
## ***Is the dataset balanced?***
*   **No, the dataset is imbalanced.**
*   **"Good"** customers constitute *70.0%* of the data, whereas **"Bad"** customers account for only *30.0%*.
*   This imbalance is significant as it may lead our future prediction model to be biased towards the majority class (**"Good"**). Consequently, it will excel at predicting "Good" customers but will struggle to accurately identify the risky ***"Bad"** customers.